apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-ai-backend
  namespace: r-ai
  labels:
    app: r-ai-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: r-ai-backend
  template:
    metadata:
      labels:
        app: r-ai-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/${GITHUB_REPOSITORY}/backend:${GIT_SHA}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_URL
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GEMINI_API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_REFRESH_SECRET
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: COOKIE_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 